feeds:
    - url: http://www.highscalability.com/rss.xml
    - url: https://blog.jessfraz.com/index.xml
      nickname: Jessie Frazelle
    - url: https://lemire.me/blog/feed/
      nickname: Daniel Lemire
    - url: http://dtrace.org/blogs/bmc/feed/
      nickname: Bryan Cantrill
    - url: https://eev.ee/feeds/blog.atom.xml
      nickname: Eevee
    - url: http://danluu.com/atom.xml
    - url: https://https.www.google.com.tedunangst.com/flak/rss
      nickname: Ted Unangst
    - url: https://programmingisterrible.com/rss
    - url: https://www.stilldrinking.org/rss/feed.xml
    - url: https://terrytao.wordpress.com/feed/
    - url: https://gowers.wordpress.com/feed/
    - url: https://www.scottaaronson.com/blog/?feed=rss2
    - url: https://mathbabe.org/feed/
    - url: https://johncarlosbaez.wordpress.com/feed/
    - url: https://thehighergeometer.wordpress.com/feed/
    - url: http://antirez.com/rss
    - url: https://blog.erratasec.com/feeds/posts/default
    - url: https://www.tedinski.com/feed.xml
    - url: https://ferd.ca/feed.rss
    - url: https://blog.acolyer.org/feed/
    - url: http://n-gate.com/index.atom
    - url: https://git.github.io/rev_news/feed.xml
    - url: https://acoup.blog/feed/
